### ISSUE TITLE
使用支付功能时报这个 

### ISSUE THREAD

**Issue by wulaizi** [uiwjs/react-native-alipay#15]
`    java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
        at com.alipay.sdk.app.PayTask.a(SourceFile:104)
        at com.alipay.sdk.app.PayTask.payV2(SourceFile:185)
        at com.uiwjs.alipay.RNAlipayModule$2.run(RNAlipayModule.java:65)
        at java.lang.Thread.run(Thread.java:919)`

**Comment by wulaizi** [comment]
安卓 rn版本"react-native": "0.63.2",

**Comment by wulaizi** [comment]
找到错误原因 我自己的原因 传了个undefined进去
