### ISSUE TITLE
yarn add 安装依赖包后，编译报如下错误，导致工程无法运行

### ISSUE THREAD

**Issue by yiyou1992** [uiwjs/react-native-alipay#61]
1: Task failed with an exception.
-----------
* Where:
Build file 'D:\Project\xbov-dp-mobile\node_modules\@uiw\react-native-alipay\android\build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':uiw_react-native-alipay'.
> Plugin with id 'maven' not found.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

2: Task failed with an exception.
-----------
* What went wrong:
A problem occurred configuring project ':uiw_react-native-alipay'.
> compileSdkVersion is not specified. Please add it to build.gradle

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
==============================================================================

* Get more help at https://help.gradle.org

BUILD FAILED in 14s

    at makeError (D:\Project\xbov-dp-mobile\node_modules\execa\index.js:174:9)
    at D:\Project\xbov-dp-mobile\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\Project\xbov-dp-mobile\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\Project\xbov-dp-mobile\node_modules\@react-native-community\cli\build\index.js:192:9)
info Run CLI with --verbose flag for more details.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by sunan112** [comment]
+1

**Comment by jaywcjlove** [comment]
https://github.com/uiwjs/react-native-alipay/issues/61

我觉得可能要回滚代码 @sunan112 @yiyou1992

**Comment by sunan112** [comment]
可以给个方案吗，新建一个空项目就能复现这个问题

**Comment by jaywcjlove** [comment]
@sunan112 使用 `v4.0.3` 版本

**Comment by jaywcjlove** [comment]
使用 v5  安装 maven 使用，我觉得需要回滚。

**Comment by jaywcjlove** [comment]
https://opendocs.alipay.com/common/02km9l#15.8.11

官方已经不提供 SDK下载了，看样子还不能回滚。


<img width="719" alt="image" src="https://user-images.githubusercontent.com/1680273/183044120-9667b977-4a40-41c3-af1a-866207aa4401.png">

**Comment by jaywcjlove** [comment]
`Gradle 7` 版本将 `maven` 插件移除了，用 `maven publish` 插件替代。你的 `Gradle 7` 版本太高，我发一个新版本，支持最新的。

**Comment by jaywcjlove** [comment]
@sunan112 升级 `@uiw/react-native-alipay@5.0.1` 试试看

**Comment by sunan112** [comment]
好的，多谢大佬，我试一下
